MIN_IMG_SCALE = 0.1
MAX_IMG_SCALE = 1

INIT_L = 50
INIT_Z = 25
DEFAULT_WAVELENGTH = 0.633 # MICRONS
DEFAULT_DXY = 3.5 # MICRONS

MAX_WIDTH = 800
MAX_HEIGHT = 600

MIN_L = 0 # MICRONS
MAX_L = 100 # MICRONS

MIN_Z = 0 # MICRONS
MAX_Z = 100 # MICRONS

MENU_FRAME_WIDTH = 450
MENU_BUTTONS_HEIGHT = 80

PARAMETER_FRAME_WIDTH = 450

PARAMETER_FRAME_HEIGHT = 80

PARAMETER_ENTRY_WIDTH = 70
PARAMETER_BUTTON_WIDTH = 10

SLIDER_HEIGHT = 10
